### PR TITLE
Adds spaces to the operators for CSS calc functions.

### PR DESCRIPTION
**Pull request by own3mall**
Fixes the issue reported multiple times regarding css calc functions needed space for the operators.

https://github.com/yui/yuicompressor/issues/244

### CODE REVIEW

**Comment by own3mall** [comment]
#244 is related to #59

**Comment by own3mall** [comment]
Sorry, I'm new to GitHub and didn't realize that it would include every additional commit I make.  You could always just merge the first commit c7ca67f into your branch assuming the changes are acceptable.

**Comment by own3mall** [comment]
Needs the latest commit too though.

**Comment by mattfurtado** [comment]
@own3mall Any updates on this?

**Comment by tyuuni** [comment]
Any ideas about how soon this change will be released?

**Comment by milushov** [comment]
wow

Guys why was the last release 5 years ago? A lot of people in #59 are still complaining, why can't we release new version with fixes? Do you need help with something?

@tml @sdesai @davglass

**Comment by Chris2011** [comment]
It is easy, they don't work anymore on the YUICompressor. So it seems deprecated IMHO.

**Comment by tml** [comment]
My current employer has no dependencies on YUICompressor, which makes it much more difficult to make time for working on it. Additionally, most people these days seem to be writing constructs in versions of JavaScript that YUICompressor frankly cannot support without a complete rewrite; the version of Rhino that YUICompressor relies on doesn't support anything beyond ECMAScript 3, and versions of Rhino past that broke the APIs YUICompressor used. So without a complete rewrite to the new Rhino API, there's not much point in doing a new release.

**Pull request merged**
