### PR TITLE
Add default gitattributes suggested by github

### PR DESCRIPTION
**Pull request by hazendaz**
ensure normalization of line endings - only one file needed corrected
which was automatic.

### CODE REVIEW

**Comment by hazendaz** [comment]
Any status on this PR?

**Comment by tml** [comment]
Not entirely sure what the benefit is to having gitattributes defined for a bunch of filetypes that aren't relevant to YUICompressor - maybe you could elaborate?

**Comment by hazendaz** [comment]
Line normalization is all that matters.  Github creates the file though which is why other stuff is there.  I certainly can remove the extra elements if that helps.

--- Original Message ---

**Comment by tml** [comment]
That would be great, if it's not too much trouble. Thank you!

**Comment by hazendaz** [comment]
Git attributes now only has line normalization and git ignores has a couple elements for eclipse.

**Pull request merged**
