### PR TITLE
fix some minification errors related to zero value replacements

### PR DESCRIPTION
**Pull request by jochenberger**
This relates to (i.e. fixes) #151 (with duplicates), #221, #222.
It causes some tests to fail though, so this probably needs some more work before it can be merged. It should help to start s discussion though.

### CODE REVIEW

**Comment by jochenberger** [comment]
Could it be that the node tests confuse the expected and actual results?

**Comment by txtszas** [comment]
+1

**Comment by jochenberger** [comment]
Also fixes #113 and #162

**Comment by jochenberger** [comment]
and #80

**Comment by mattfurtado** [comment]
Any updates on this? Would greatly appreciate a fix for this issue!

**Comment by jochenberger** [comment]
@tml What's holding this back?

**Comment by mattfurtado** [comment]
@tml @jochenberger Checking in once again 😄

**Pull request merged**
